### ISSUE TITLE
Use Docker directly from the docker release tar

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#393]
Currently we rely for Docker on the available Docker versions inside the package management systems of the operating systems. There we either use it from the operating system repositories or we include the docker repository.

This has the downside that we cannot install the latest, validated Docker version for the requested Kubernetes version.

Example 1:
In the Ubuntu bionic repositories only Docker 17.12 exists. 
In the upstream Docker repo for Bionic only 18.04 exists.
The latest validated Docker version for Kubernetes v1.9-1.11 is 17.03

Example 2:
CoreOS uses always a very specific Docker version - There is no way to use a different version, than the one CoreOS ships with. With the current stable CoreOS release (`1855.5.0`) Docker 18.06.1 gets used.

To avoid this situation, Docker should be installed via Binary.
The binaries can be downloaded from https://download.docker.com/linux/static/stable/x86_64/

**Tasks**
- [ ] Docker binaries gets downloaded from the above mentioned URL
- [ ] A systemd unit gets written for each operating system
- [ ] All dependencies for Docker will be installed via the package management systems (See [kops nodeup for the relevant dependencies](https://github.com/kubernetes/kops/blob/842c925d7f6195c86aae6dffe0f018136e864e99/nodeup/pkg/model/docker.go#L426))
- [ ] All docker daemons use the same `daemon.json`

**Comment by mrIncompetent** [comment]
@mrIncompetent needs clarification (Since we had this but reverted it - due to the userdata size)
