### ISSUE TITLE
Support for Ubuntu 20.04

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/machine-controller#832]
The goal of this task is to provide support for Ubuntu 20.04. Currently only Ubuntu 18.04 is officially supported.

- [ ]  Verify that the right deb docker repository is used. Currently we are targeting bionic (18.04).
- [ ] Add e2e tests for Ubuntu 20.04.
- [ ] Verify that nothing else in the cloud-init config should be changed.
- [ ] Update supported OS matrix.
- [ ] Update documentation.

**Comment by irozzo-1A** [comment]
xref: https://github.com/kubermatic/machine-controller/issues/839
